### PR TITLE
Add seL4 12.1.0 manual

### PR DESCRIPTION
**Pull request by nomadeel**
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]

**Review by axel-h — CHANGES_REQUESTED** [review]
please also update the symlink `content/Info/Docs/seL4-manual-latest.pdf`. Seems this has been neglected for a while, it points to ` seL4-manual-11.0.0.pdf`.

Also, I wonder if the manual should the an "seL4 Foundation" branding now. But this might be an update we can do later also.

**Comment by axel-h** [comment]
https://github.com/seL4/seL4/pull/390 adds seL4 Foundation branding for the manual

**Comment by axel-h** [comment]
Is this waiting for the new manual now?

**Comment by lsf37** [comment]
This is mostly waiting for Damon to have time to come up for air :-). I think the 12.1.0 release should still get the old manual, given that we changed the branding after the release was out.

I can have a look at the link

**Comment by lsf37** [comment]
(rebased and added symlink)

**Comment by lsf37** [comment]
@axel-h if you change your review to approve, you can merge this change directly.

The validator failure is unrelated, and I think being fixed in one of the other PRs.

**Review by axel-h — APPROVED** [review]

**Pull request merged**
