### PR TITLE
Fix summit year links

### PR DESCRIPTION
**Pull request by bbrcknl**

### CODE REVIEW

**Comment by june-andronick** [comment]
thanks @bbrcknl . I think this would fix the issues that @gernotheiser raised. My only comment is that the landing page with all summits has completely disappeared, even in the path shown at the top of a summit page: it used to be  "Home / seL4 Foundation / seL4 Summit / 2023" and it's now "Home / seL4 Foundation / 2023". This is (a) a bit confusing because you now just have  a year without the mention of "summit" in that path and (b) you don't have anything linking to this landing page with all the summits. Not sure how this can be fixed but if we need at least one link to the landing page to make this work, I would add "All" at the end of "Other summit editions: 2022" (even if, as we discussed, it is not yet very useful)

**Comment by bbrcknl** [comment]
@june-andronick I've replaced the code that ignored "Summit" in the breadcrumb. I've also added and "all" in the Editions section for both 2022 and 2023.

**Comment by june-andronick** [comment]
Thanks @bbrcknl. I would just add a comma and a capital in "2022, All" and "2023, All". Maybe actually "All years" even.

With that, I think it meets all what we were after.  @gernotheiser can you please check that this is what you wanted?

I'm approving this so @bbrcknl you can merge once gernot confirms he's happy with it

**Review by june-andronick — APPROVED** [review]

**Comment by gernotheiser** [comment]
Pretty much. I would simplify the link to other summits, and just have a single "all Summits" link go to the landing page. I don't see much benefit of having multiple links there, and it's harder to maintain.

**Comment by june-andronick** [comment]
> Pretty much. I would simplify the link to other summits, and just have a single "all Summits" link go to the landing page. I don't see much benefit of having multiple links there, and it's harder to maintain.

Good point. I'd be happy with that.

**Pull request merged**
