### PR TITLE
Direct link to endorsed service providers

### PR DESCRIPTION
**Pull request by lsf37**
Provide a direct link/button from the home page to endorsed service provides.

Takes the spot where "Contributions" was before and shifts that further down.

### CODE REVIEW

**Comment by lsf37** [comment]
New look is this:
Screenshot 2023-03-31 at 11 04 41

**Comment by gernotheiser** [comment]
I suggest making consistent changes to the menu bar. Right now under "Foundation" there is "endorsed service providers" which is the same but worded differently. I think that menu bar might do with some restructuring anyway. Eg the "Use" isn't what I'd expect, and takes up a whole top-level menu slot

**Comment by june-andronick** [comment]
Thanks for doing this @lsf37 

I agree with the suggestion to change the drop down menu text from "Endorsed Service providers" to "Commercial support".

I would also suggest to change the "Support the Foundation" to "Support seL4".

**Comment by lsf37** [comment]
Have done the updates (updated menu and page titles, and changed to "Support seL4").

Agree that the "Use" button and menu point is a bit out of place. Will leave that to a separate PR, it needs a bit more  thinking. As a user I'd expect here some examples on how to use seL4, what user-level platforms are available (CP, CamkES, Kry10, TrentOS, others) and what languages are supported, and how to get started with things (links to tutorials and docs). Might also be a place to cross-link to the white paper again for those who want a broader overview.

**Review by gernotheiser — APPROVED** [review]
Looks fine.
Not directly relevant, but related issue: The Research and Roadmap pages are in desperate need of love

**Pull request merged**
