### PR TITLE
Testing if html5 output is nicer

### PR DESCRIPTION
**Pull request by LukeMondy**
Signed-off-by: Luke Mondy <luke.mondy@data61.csiro.au>

### CODE REVIEW

**Comment by lsf37** [comment]
Interesting! The commenter fails for you as well. So maybe it's not rights, but an actual bug somewhere.

**Comment by LukeMondy** [comment]
Also, my fix didn't actually fix the issue :|
https://github.com/seL4/website_pr_hosting/blob/PR_35/localhost/pr_checks/validator.log

**Comment by lsf37** [comment]
It looks like our sed change hasn't had the desired effect either, unfortunately: https://htmlpreview.github.io/?https://github.com/seL4/website_pr_hosting/blob/PR_35/localhost/pr_checks/validator.log

**Comment by LukeMondy** [comment]
I will have to come back to this tomorrow, sorry. 
Bloody thing <shakes fist>

**Comment by lsf37** [comment]
No worries. I'm not seeing it either at the moment.

**Comment by wom-bat** [comment]
Any reason I shouldn't delete this PR?

**Comment by lsf37** [comment]
Ok to close from my side. @LukeMondy are you still monitoring these?

In the meantime, GitHub changed how it passes information around for the commenter, so there are new glitches we should look at. Not urgent, though.

**Comment by lsf37** [comment]
Actually, this is just a test, so it can be closed anyway.

**Pull request closed without merging**
