### PR TITLE
adding nio job ad

### PR DESCRIPTION
**Pull request by june-andronick**
Signed-off-by: June Andronick <june@sel4.systems>

### CODE REVIEW

**Comment by june-andronick** [comment]
Not sure about the issues here:
- html5 issue are on files I didn't touch (home and news)
- not sure what the license issue is
- the link error is about a link that works for me...

**Comment by gernotheiser** [comment]
The HTML issues seem to have been introduced by the release news item. They are being fixed in my PR for the Board minutes, but I might as well add them in here too.

**Review by gernotheiser — APPROVED** [review]
Looks good. Please replace the PNG with the SVG logo once we receive it.

**Comment by gernotheiser** [comment]
ok, no SVG, we'll have to go with what's there.

**Pull request merged**
