### PR TITLE
Use more reliable method to comment on PRs

### PR DESCRIPTION
**Pull request by LukeMondy**
Test PR from forked repo

### CODE REVIEW

**Comment by LukeMondy** [comment]
Almost worked.

I think we should switch the github action for commenting from the current one, to instead use `github-script`. They even have commenting as an example: https://github.com/actions/github-script

There is an example in this action too: https://github.com/marketplace/actions/comment-on-pr

I will try it out on my fork.

**Comment by lsf37** [comment]
Getting there! Yes, the `script` action looks reasonable for this.

**Comment by LukeMondy** [comment]
I think this is working now.

**Review by lsf37 — APPROVED** [review]
Cool, this is looking good!

We should probably run another test from a fork after this is merged.

**Comment by LukeMondy** [comment]
Yep, agreed.

**Pull request merged**
