### PR TITLE
Update endorsements page

### PR DESCRIPTION
**Pull request by bbrcknl**

### CODE REVIEW

**Comment by june-andronick** [comment]
Thanks Birg! Few suggestions:
- move the whole paragraph form "The type of services that the member..." to "for free" to either the bottom of the page or a new page, under the title "Information about the endorsement scheme"
- replace the above paragraph (just after "and development services around seL4.") with a new paragraph, if possible in some bold/emphasis: "Below are the seL4 Service Providers that are endorsed by the seL4 Foundation." Then a new paragraph: "If you are a member and would like to be endorsed, please <contact us>. You can find more information on the endorsement scheme <here>. If you are not a member yet, you can join <here>."
- in the drop down menu: (a) change "Services" for "Endorsed Service Providers" and (b) change its position to be at the same location than in the list in the Foundation/home page
- on HC's separate service pages, change "Additionally, the seL4 Foundation assessed and endorsed" with "Additionally, the seL4 Foundation has previously assessed and endorsed"
- not sure why but the separate HC page has "Coq | seL4" at the same of the tab in a browser...

**Comment by bbrcknl** [comment]
@gernotheiser @lsf37 Does adding "Endorsed Service Provider" under member logos look too clunky?

**Comment by gernotheiser** [comment]
looks fine to me

**Comment by lsf37** [comment]
> @gernotheiser @lsf37 Does adding "Endorsed Service Provider" under member logos look too clunky?

Currently it shifts the logos, which doesn't look good. If you can swing it so that the alignment stays the same, I think it's good.

**Comment by bbrcknl** [comment]
Thanks! I'll play with it some more on Wed, and then do a PR.

**Review by lsf37 — APPROVED** [review]
Looks good!

**Pull request merged**
