### PR TITLE
adding news item for seL4 day

### PR DESCRIPTION
**Pull request by june-andronick**
Signed-off-by: June Andronick <june@sel4.systems>

### CODE REVIEW

**Comment by june-andronick** [comment]
There's an issue with the license of the picture I added. It's from your blog @gernotheiser. I don't know how to fix the issue. We can remove the picture if needed.

**Comment by axel-h** [comment]
@june: How much of social media a campaign do you plan there? I could ask our marketing department to also do a post (unless this has not been done already)

**Comment by lsf37** [comment]
> There's an issue with the license of the picture I added. It's from your blog @gernotheiser. I don't know how to fix the issue. We can remove the picture if needed.

You need to add a file `content/images/sel4-birthdaycake.png` similar to the other `.license` files in the `images/` directory. You can also add a license to the global `.reuse/dep5` file, but a `.lincese` file is nicer for this one. The file should have a Copyright line with whoever owns the copyright on the picture, and a license line, which by default should be CC-BY-SA-4.0 or whatever the image license is if it is constrained by something.

**Comment by lsf37** [comment]
> @june: How much of social media a campaign do you plan there? I could ask our marketing department to also do a post (unless this has not been done already)

I think that would be cool. @gernotheiser and @june-andronick what do you think?

**Review by lsf37 — APPROVED** [review]

**Comment by gernotheiser** [comment]
> > There's an issue with the license of the picture I added. It's from your blog @gernotheiser. I don't know how to fix the issue. We can remove the picture if needed.
> 
> You need to add a file `content/images/sel4-birthdaycake.png` similar to the other `.license` files in the `images/` directory. You can also add a license to the global `.reuse/dep5` file, but a `.lincese` file is nicer for this one. The file should have a Copyright line with whoever owns the copyright on the picture, and a license line, which by default should be CC-BY-SA-4.0 or whatever the image license is if it is constrained by something.

I took that picture myself and am definitely happy to copyleft it.

**Comment by gernotheiser** [comment]
> > @june: How much of social media a campaign do you plan there? I could ask our marketing department to also do a post (unless this has not been done already)
> 
> I think that would be cool. @gernotheiser and @june-andronick what do you think?

Sure, the more the merrier. I'll send a brief mail to PR contacts in case anyone else wants to do anything. Thanks for suggesting, @axel-h

**Comment by gernotheiser** [comment]
@ikuz should have an alumnus page on TS, but in the move we seem to have lost all of those. We'll get them back. For now we'll probably best just ignore that broken link

**Pull request merged**
