### PR TITLE
Add crowdfunding to Support

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
Again, slow loads but all links look good

**Comment by lsf37** [comment]
That ETH link is really strange. It loads in the browser just fine, but with `wget` I reproducibly get:
```
$ wget https://ethz.ch/en.html
--2021-04-18 20:16:51--  https://ethz.ch/en.html
Resolving ethz.ch (ethz.ch)... 129.132.19.216
Connecting to ethz.ch (ethz.ch)|129.132.19.216|:443... connected.
HTTP request sent, awaiting response... 404 Not found UA
2021-04-18 20:16:52 ERROR 404: Not found UA.
```

**Comment by lsf37** [comment]
And it works with `curl`..

**Comment by lsf37** [comment]
The site is checking the user agent. E.g. this works:
```
wget --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" https://ethz.ch/en.html
```

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
