### PR TITLE
Update HC board member to Olivier

### PR DESCRIPTION
**Pull request by june-andronick**

### CODE REVIEW

**Comment by june-andronick** [comment]
Linker issue is the usual occasional timeout from nio's website. This is ready to go if @gernotheiser you're happy with it

**Comment by gernotheiser** [comment]
The non office bearers should be ordered by first name

**Comment by june-andronick** [comment]
> The non office bearers should be ordered by first name

Order fixed

**Review by gernotheiser — APPROVED** [review]
LGTM

**Comment by axel-h** [comment]
Since Sascha has left the board, delete the pictures from him?
- `content/Foundation/Board/HC-Sascha-s.jpg`
- `content/Foundation/Board/HC-Sascha.jpg`

**Pull request merged**
