### PR TITLE
fix layout and small improvement

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by gernotheiser** [comment]
I noticed the missing <strong> tag when working on another PR – mea culpa.

Hard to judge the nicing part without a preview.

**Comment by gernotheiser** [comment]
That exceeds my present pain limit ;-)

Should I simply add it to my other PR (#99) and check the preview there?

**Comment by lsf37** [comment]
That would work too

**Comment by gernotheiser** [comment]
OK, tested on #99, looks good.

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
