### PR TITLE
Add summit video links

### PR DESCRIPTION
**Pull request by bbrcknl**

### CODE REVIEW

**Comment by gernotheiser** [comment]
Please remove "preliminary" from "Preliminary Program"

**Comment by gernotheiser** [comment]
Please use the proper handle for the Youtube channel: https://youtube.com/@seL4

**Review by june-andronick — APPROVED** [review]
This looks good to me! The display in the program looks really neat. Thanks for the hard work!

The commit for the board minutes seems to still be there. Not sure whether you had planned to remove it and do it separately or do that next time.

Also the linker issue seems real. XCalibyte's website seems to have a problem. I've emailed them.

Once that's fixed, it's fine by me.

**Comment by bbrcknl** [comment]
@june-andronick Do you want me to comment out all the XCalibyte links before the push and merge?
I'll take out the board commits (one for adding and one for removing minutes) in my squash and merge.

**Comment by june-andronick** [comment]
ok it's all good now. I'll leave you to do the merge @bbrcknl and select what commits you want to remove. Thanks!

**Comment by gernotheiser** [comment]
It still says "preliminary program" and the news item doesn't use the new named Youtube handle

**Comment by june-andronick** [comment]
> It still says "preliminary program" and the news item doesn't use the new named Youtube handle

@gernotheiser : I see this fixed in Birg's latest commit.

**Pull request merged**
