### PR TITLE
Add Xcalibyte news item

### PR DESCRIPTION
**Pull request by gernotheiser**
This is the first of 3 or 4 joining at the same time, which may or may
not end up as separate announcements. In any case this needs to wait
until the update to the members page is merged.

Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
Logo link breakage is expected, as long as the members page update isn't merged

**Comment by june-andronick** [comment]
The description has SEL4 rather than seL4.

**Review by june-andronick — APPROVED** [review]

**Comment by gernotheiser** [comment]
Logo link should work once the live site updates (within an hour)

**Comment by gernotheiser** [comment]
Life site is updated, ready to go out

**Pull request merged**
