### PR TITLE
Add unconfirmed minutes of 5th MB

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
I won't push those before Sunday to give Board members a chance to identify issues

**Review by june-andronick — APPROVED** [review]
All good

**Comment by axel-h** [comment]
Please change Haider -> Heider in the PDF.

**Comment by gernotheiser** [comment]
Oops, sorry!

**Comment by gernotheiser** [comment]
Needed to squash as intermediate commits conflicted with master

**Pull request merged**
