### PR TITLE
Colour scheme

### PR DESCRIPTION
**Pull request by lsf37**
Experimenting with moving more colours to `seL4.css` and changing to foundation colour scheme.

Might make more sense to re-generate bootstrap.min.css with that colour scheme, but let's see how far this carries.

### CODE REVIEW

**Comment by lsf37** [comment]
The bot should have said: Preview your changes [here](https://htmlpreview.github.io/?https://github.com/seL4/website_pr_hosting/blob/PR_24/localhost/index.html)

**Comment by LukeMondy** [comment]
@lsf37 looks like something has changed with the GitHub VMs?
Looking at the raw log, it's complaining about not knowing about 'ubuntu-latest', and the GitHub Script part doesn't even seem to run.
Do you know about this?

**Comment by lsf37** [comment]
Yes, something has definitely changed in the github VMs, I've had a lot of fun updating other CI actions for python version confusion and stuff. It did still know about ubuntu-latest yesterday, though.

**Comment by LukeMondy** [comment]
No worries, I will try to check it out asap.

**Comment by lsf37** [comment]
Now ready for review.

**Comment by lsf37** [comment]
(The preview hasn't really caught up yet, at least for me -- maybe it works if the old version isn't cached)

**Comment by LukeMondy** [comment]
Ah yeah, opening it in a private tab helped me see the latest version.

**Review by LukeMondy — APPROVED** [review]
Looks good!

**Pull request merged**
