### PR TITLE
Fix casing of MicroPython

### PR DESCRIPTION
**Pull request by JE-Archer**

### CODE REVIEW

**Comment by lsf37** [comment]
Please don't commit served content that fails the license or html validation check. This is probably from a previous version and not this PR, but it is definitely against LF policy.

**Comment by Ivan-Velickovic** [comment]
> Please don't commit served content that fails the license or html validation check. This is probably from a previous version and not this PR, but it is definitely against LF policy.

I thought it was okay because it's a branch, or is it not okay in either case?

**Comment by lsf37** [comment]
> > Please don't commit served content that fails the license or html validation check. This is probably from a previous version and not this PR, but it is definitely against LF policy.
> 
> I thought it was okay because it's a branch, or is it not okay in either case?

It's served publicly under the foundation domain, no? If it's not just a development branch, the policies definitely all apply. I'll set up a branch protection rule for it.

**Comment by Ivan-Velickovic** [comment]
Understood. I'll make a PR now to fix it.

**Pull request merged**
