### PR TITLE
Trim whitespace of DW logo

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

Thanks MattB

### CODE REVIEW

**Comment by gernotheiser** [comment]
The linklint fails ahve nothing to do with this commit, but are annoying nevertheless:
- https://www.universite-paris-saclay.fr/en: June's alma mater vanished?
- https://ts.data61.csiro.au/projects/seL4/: I thought adding the extension was fixed?
- https://ts.data61.csiro.au/publications/papers/Kuz_19.abstract.pml: not sure what's the issue with that one

**Comment by gernotheiser** [comment]
WIth all the excessive whitespace removed from the logos, the rows are too close, there needs to be a bit extra vertical space. Need to look at the CSS, sigh...

**Comment by wom-bat** [comment]
>>>>> "Gernot" == Gernot Heiser <notifications@github.com> writes:

Gernot> to do with this commit, but are annoying nevertheless: -
Gernot> https://www.universite-paris-saclay.fr/en: June's alma mater
Gernot> vanished?
It's *really* slow ... and pops up a dialogue you ghave to accept
before the page can be loaded.

- https://ts.data61.csiro.au/projects/seL4/: I
Fixed.
Gernot> thought adding the extension was fixed?  -
Gernot> https://ts.data61.csiro.au/publications/papers/Kuz_19.abstract.pml:
Gernot> not sure what's the issue with that one

Ditch the .pml on the end.
-- 
Peter Chubb
Principal Research Engineer | Trustworthy Systems | Data61 | CSIRO
 +61 2 9490 5852 | http://ts.data61.csiro.au/

**Review by june-andronick — APPROVED** [review]
Fine with it once spacing is fixed.

**Comment by gernotheiser** [comment]
Not sure it's what I want, but the preview seems unreliably. Merging now and may have to fix again

**Pull request merged**
