### PR TITLE
add a logo pack

### PR DESCRIPTION
**Pull request by lsf37**
This PR adds a logo pack download page to the site.

In a separate commit, it also switches the font to the foundation style (Roboto).

### CODE REVIEW

**Comment by lsf37** [comment]
Latest preview [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/seL4/website_pr_hosting/PR_40/localhost/Foundation/Trademark/logo.pml.html)

**Comment by gernotheiser** [comment]
Fonts look nice, very clean.
In the logo pack, is it intentional that the PDF version of the logo is much larger than the logo (i.e. not clipped to the min size)?

**Comment by lsf37** [comment]
> In the logo pack, is it intentional that the PDF version of the logo is much larger than the logo (i.e. not clipped to the min size)?

Well spotted, it wasn't intentional, I just copied what we had before.

There is a case to be made for leaving it unclipped, because it makes it harder to not have whitespace around the logo in print, but I'm tending to just making it consistent with the others and clipping it fully so it's easier to handle.

Do you have an opinion on this? @june-andronick what do you think?

**Comment by gernotheiser** [comment]
The inconsistency between the PDF and the PNG is not good no matter what, and the PNG is clipped.
Leaving some amount of whitespace around the logo is good, but given that the PDF has transparent background (which is good) this doesn't actually do much, other than giving a hint to the user. 
I personally clip any pictures I receive before doing anything else with them ;-) And I also occasionally use the logo without much space around it, eg in slides where it's in a box representing the kernel (where I keep the box as thin as possible to indicate its small size).

**Comment by june-andronick** [comment]
Main comments: it's missing the Foundation logo (while the readme says it contains it) and we probably want to add the other variants (white logo, black logo... but also the one with tag line in pdf/svn). 
Note: Kim shared with me a drive folder with all the stuff she worked on for the foundation, in case you want it.

Regarding being clipped, I don't quite understand why you would want it unclipped. You always want as little as possible around, don't you? Another option would be tp have 2 versions, clipped and unclipped, but I would definitely make the pdf a bit less unclipped ;)

**Comment by lsf37** [comment]
Ok, changed PDF to clipped so everything is consistent, added the other formats for the tagline sticker logo, and fixed up the README in the zip file.

And I've figured out what the link checker is always complaining about: we have a "canonical" link ref in every page which says where the source version of this page can be found. This always points directly to sel4.systems. If you add a new page, that new page does of course not yet exist on sel4.systems, hence the error. We need to patch those links to the preview site instead before we run the link checker. I can have a look at that tomorrow.

That explains why the link checker is failing for anything with a new page, but it does not yet explain why the comment posting falls over as soon as there is link checker output, instead of nicely linking to the link checker output. I've seen it work before, so maybe something changed on the github end, but we do use a fixed version of the corresponding github action, so it should not randomly change.

I'll ping @LukeMondy here in case he knows something and so he can find it again in that mythical future where there is more time for such things.

**Comment by lsf37** [comment]
Ok, the last commit seems to have fixed the link checker complaining about new files at least.

The PR is ready for merge if you're happy with it @gernotheiser and @june-andronick

**Review by gernotheiser — APPROVED** [review]

**Pull request merged**
