### PR TITLE
Add DEF CON news item

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
linklint fail is expeected – awaiting SMACCMcopter pix

**Review by lsf37 — APPROVED** [review]
Looks good. Only question is if we really want to spell out FTW. Kinda takes away from using it in the first place.

**Comment by lsf37** [comment]
(Oh, and still needs a `.license` file for the pic)

**Comment by gernotheiser** [comment]
Yes, waiting for Darren about the licensing conditions. The pic was posted on Twitter by DARPA, not sure what that means

**Comment by lsf37** [comment]
> Yes, waiting for Darren about the licensing conditions. The pic was posted on Twitter by DARPA, not sure what that means

Doesn't help much. Only means that they had the right to post it, not that anyone else can use it.

I guess we could make a `LicenseRef-UsedWithPermission.txt` file that says "All rights reserved by copyright holder, used with permission on this website". That should make clear it's not free for re-use and the ref can then be used for other such pictures as well.

**Pull request merged**
