### PR TITLE
Raytheon

### PR DESCRIPTION
**Pull request by gernotheiser**
Adding the Raytheon logo to the members page

### CODE REVIEW

**Comment by gernotheiser** [comment]
The linklint fails are http://trustworthy.systems being broken, and paper abstract files having vanished. Nothing to do with the PR

**Comment by gernotheiser** [comment]
The preview seems to be missing its style file, should ahve nothing to do with me

**Review by lsf37 — APPROVED** [review]
Looks fine to merge from here. Not sure what's up with the preview, the CSS is there, but it doesn't seem to be loaded.

**Comment by gernotheiser** [comment]
magically the preview layout has fixed itself.
I think we should make the Raytheon logo a bit bigger, making everything the same width makes it quite small. We should probably aim for roughly equal area (and one of these years HC will get a proper logo too...)

**Comment by gernotheiser** [comment]
Increasing the size of the Raytheon logo by 50% makes things look more balanced IMHO

**Comment by lsf37** [comment]
It's now a bit larger than the others. 33%? I'm fine with either, though.

**Comment by lsf37** [comment]
> magically the preview layout has fixed itself.

It still doesn't work for me, although the page code itself seems correct. It shows `../css/sel4.css` as the link to the css. When you follow the link on the GitHub preview, it seems to change it to `/css/sel4.css`, which is too far up. Not sure what to do about it at this stage. If it works for you, maybe we should leave it as is for now.

**Comment by gernotheiser** [comment]
Bizarre. Ill merge it now

**Comment by june-andronick** [comment]
Looks good to me. Thanks.
I'll work on the announcement with them.

**Pull request merged**
