### PR TITLE
Add Penten to members page

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
Not sure why the trailing-whitespace test fails, there ain't any in the files I committed.

**Comment by lsf37** [comment]
> Not sure why the trailing-whitespace test fails, there ain't any in the files I committed.

If you click on details and then the red failing section, it'll tell you. It looks like one of the svg files has a lot of trailing whitespace in it (it's just a text file). It's not critical (could be ignored if you like), but better to remove.

**Comment by gernotheiser** [comment]
I did load that svg into the editor and could not see any trailing whitespace. I believe it points to the last non-empty line, and there’s nothing AFAICT.

On 2 Feb 2021, at 08:43, Gerwin Klein <notifications@github.com<mailto:notifications@github.com>> wrote:



Not sure why the trailing-whitespace test fails, there ain't any in the files I committed.

If you click on details and then the red failing section, it'll tell you. It looks like one of the svg files has a lot of trailing whitespace in it (it's just a text file). It's not critical (could be ignored if you like), but better to remove.

**Comment by lsf37** [comment]
> I did load that svg into the editor and could not see any trailing whitespace. I believe it points to the last non-empty line, and there’s nothing AFAICT.

It was using `\n\r` instead of `\n` line endings, and the additional `\r` shows up as whitespace. I've pushed a fix.

**Review by lsf37 — APPROVED** [review]
Looks good from here.

**Comment by gernotheiser** [comment]
Argh, didn't think of that, thanks.

**Comment by gernotheiser** [comment]
The excess vertical space is nothing to do with Penten, but the DornerWorks logo needs clipping. My quick attempt failed, maybe someone else can have a go.

**Pull request merged**
