### PR TITLE
update note on hangout times

### PR DESCRIPTION
**Pull request by bbrcknl**

### CODE REVIEW

**Review by june-andronick — APPROVED** [review]
Looks good, thanks @bbrcknl. The link error is not just the defcon this time, but also Data61's link that seems to have been changed. I suggest you just remove the link itself from that news item.

For the defcon link, we should really do something about it. We could try just linking to https://defcon.org. Else we could maybe link to http://loonwerks.com/publications/cofer2021defcon.html. Or can we add it as an exception? @lsf37 thoughts?

**Comment by bbrcknl** [comment]
@june-andronick All the defcon links time out, so I put the loonwerks link there instead.

**Comment by lsf37** [comment]
Sorry, I was a bit late on this one.

> @june-andronick All the defcon links time out, so I put the loonwerks link there instead.

They do all work interactively, though. They probably time out on the link checker, because they have DOS protection on the site and don't like bots. It doesn't really make sense to have the link going to loonwerks when the link text is `DEF CON`.

I think we should move it back in, but add it to the exception list for the link checker. The exception list is [here](https://github.com/seL4/website/blob/786e3aa2384082d0a1a5abb73a73ab300bff7a9e/docker/linkchecker.sh#L23-L31) in `website/docker/linkchecker.sh`.

**Comment by bbrcknl** [comment]
@lsf37 Thanks for that. I'll put the old defcon link back in and add it to the exception list.

**Pull request merged**
