### PR TITLE
css: new link colour

### PR DESCRIPTION
**Pull request by lsf37**
This colour is the same hue as neutral/neutralLight, but sits between them
in saturation and lightness. Should have better contrast with the rest of
the text, but still be readable on white.

Should hopefully fix issue #31.

### CODE REVIEW

**Comment by lsf37** [comment]
(I'm still keeping the darker-on-hover, because it increases contrast to the background and should make it more easy to read for people who have trouble in that direction).

**Comment by june-andronick** [comment]
I prefer that colour to the previous one yes. I find it still slightly too close to the default black so not completely obvious to spot but much better than before

**Review by june-andronick — APPROVED** [review]

**Review by xurtis — APPROVED** [review]
It's an improvement, I can tell which things are links now. It is looking like it might be to low contrast given when put on a white background now given the weight of the text though. We'll see how it goes I guess.

**Comment by lsf37** [comment]
Alright, let's see how it goes, and we can always update again. We could for instance increase the font weight a small bit for links, which should make it more readable against white.

**Pull request merged**
