### PR TITLE
Add social media links to footer

### PR DESCRIPTION
**Pull request by bbrcknl**

### CODE REVIEW

**Review by june-andronick — APPROVED** [review]
Looks good to me, thanks Birg!

**Comment by bbrcknl** [comment]
Social links in footer

**Comment by lsf37** [comment]
Please don't merge with validation errors. It looks like this introduces an error for all pages now (since the footer is in all page).

@bbrcknl can you fix, please?

**Comment by lsf37** [comment]
To be honest, I'm also not very happy with the layout.

I think this needs a larger change, i.e. rethinking the footer. The green line at the bottom does not work with the colours of the social media buttons, so I would vote for removing it, and just using space or slightly different background colour for separation.

Centering both the social media links and the copyright/policies makes them look like they belong together, but they don't. They need some kind of visual separation. Maybe social media on the right, and legal stuff on the left, wrapping at half page or something like that.

**Comment by bbrcknl** [comment]
From what I can see, the links checker error is:

https://htmlpreview.github.io/?https://github.com/seL4/website_pr_hosting/blob/PR_182/localhost/pr_checks/linkchecker.html

This error was introduced a few weeks ago and not by me. So, I'm not sure how to deal with it.


---

Dr. Birgit Brecknell

Project Officer

Trustworthy Systems, UNSW, ***@***.******@***.***>

seL4 Foundation, ***@***.******@***.***>

0433 880 571



Mon 9am-5pm

Wed 9am-12pm

Fri 9am-5pm

________________________________

**Comment by lsf37** [comment]
The link checker is not the problem, I mean the html5 validation. It looks like it's complaining about missing alt text for the images (which they do indeed not have).

**Comment by lsf37** [comment]
(For the link checker, the NIO links have always been flaky, maybe I should remove them from the check -- the other link it is complaining about does indeed seem to be broken and should be fixed, but not a problem of this PR)

**Comment by bbrcknl** [comment]
Ok. That's an easy fix.

Re the other changes - Would it be better if I pinged you/June when I update the footer branch? I pointed June/Gernot towards it, but Gernot couldn't see it easily and said to do a PR. I'd prefer to work on a separate branch until everyone is happy with a change.


---

Dr. Birgit Brecknell

Project Officer

Trustworthy Systems, UNSW, ***@***.******@***.***>

seL4 Foundation, ***@***.******@***.***>

0433 880 571



Mon 9am-5pm

Wed 9am-12pm

Fri 9am-5pm

________________________________

**Comment by lsf37** [comment]
> Ok. That's an easy fix. Re the other changes - Would it be better if I pinged you/June when I update the footer branch? I pointed June/Gernot towards it, but Gernot couldn't see it easily and said to do a PR. I'd prefer to work on a separate branch until everyone is happy with a change.

Happy with a branch. You can also do both, i.e. make a branch, work on that, do a pull request from that branch and keep pushing to it for updates so people can see the preview. Best to do the PR late-ish when you're reasonably confident that this is what you want to show people, and you can mark it as "draft" when it's not really ready for reviewing/merging yet.

**Comment by june-andronick** [comment]
> > Ok. That's an easy fix. Re the other changes - Would it be better if I pinged you/June when I update the footer branch? I pointed June/Gernot towards it, but Gernot couldn't see it easily and said to do a PR. I'd prefer to work on a separate branch until everyone is happy with a change.
> 
> Happy with a branch. You can also do both, i.e. make a branch, work on that, do a pull request from that branch and keep pushing to it for updates so people can see the preview. Best to do the PR late-ish when you're reasonably confident that this is what you want to show people, and you can mark it as "draft" when it's not really ready for reviewing/merging yet.

A PR on a branch is good if you want feedback on it. Else it's hard to preview.

**Comment by bbrcknl** [comment]
@lsf37 cleaned up the html5 link errors. @june-andronick was able to do her PRs. Will work on footer placement after lunch.

**Comment by lsf37** [comment]
Thanks!

**Pull request merged**
