### PR TITLE
adding news Item for interim endorsement

### PR DESCRIPTION
**Pull request by june-andronick**
Signed-off-by: June Andronick <june@sel4.systems>

### CODE REVIEW

**Comment by june-andronick** [comment]
The last linker errors seems to be from ts website. I'll assume it's ok to ignore. Ready to be reviewed by @gernotheiser

**Comment by gernotheiser** [comment]
Like with the other PR I get a server fail from htmlpreview.github.io. That doesn't look like a problem on our end

**Comment by gernotheiser** [comment]
Preview works now, but style still takes hours to load.
Content looks fine, though.

**Review by gernotheiser — APPROVED** [review]
Looks good

**Comment by gernotheiser** [comment]
don't forget to add it to the home page

**Comment by gernotheiser** [comment]
Weird, I can't actually see any of this on the preview

**Pull request merged**
