### PR TITLE
pin ruby version

### PR DESCRIPTION
**Pull request by lsf37**
- pin the ruby version to 3.3.1 (most recent stable)
- update Gemfile for 3.3.1 warnings
- update Gemfile.lock to be compatible
- use the `setup-ruby` GitHub action to get the correct ruby version in CI, including caching of dependencies.

We could actually do the pinning of ruby version in the main Gemfile here as well now, but it would still produce an error to run it with anything else, which is possibly a bit too strict. Happy for input on that one.

### CODE REVIEW

**Comment by lsf37** [comment]
Well, good that the PR checks are running everything. I had not tried the link checker. Now need to find the versions of things that work..

**Comment by lsf37** [comment]
I've checked this now with the following, and they are all working:

- Darwin Intel
- Darwin Apple Silicon
- Linux arm64 (via docker)
- Linux x86 (via docker)

The `htmlproofer` error seems to be something that starts happening in version 5 of `htmlproofer`, so I've constrained it to major version 4 in the `Gemfile`.

**Review by Indanz — APPROVED** [review]
I think it would help to document in the commit message what you did exactly to update Gemfile.lock and definitely document any manual changes you made and why. 

I would annotate all manual changes in the Gemfile.lock with explanations why it's done. (It seems you did that to get it working on Mac, but no idea if there's anything else.)

**Comment by lsf37** [comment]
> I think it would help to document in the commit message what you did exactly to update Gemfile.lock and definitely document any manual changes you made and why.
> 
> I would annotate all manual changes in the Gemfile.lock with explanations why it's done. (It seems you did that to get it working on Mac, but no idea if there's anything else.)

I made no manual changes to `Germfile.lock`, they were all the result of `bundle update` and `bundle lock --add-platform ...`. But I can add that to the commit message so we know how we got there in the future.

**Comment by lsf37** [comment]
(e.g. pinning `html-proofer` to major version for is the result of `gem "html-proofer", "~>4"` in `Gemfile`, which will cause `bundle update` to not go beyond version 4, but pick the most recent minor and patch versions)

**Comment by Indanz** [comment]
> I made no manual changes to `Germfile.lock`, they were all the result of `bundle update` and `bundle lock --add-platform ...`. But I can add that to the commit message so we know how we got there in the future.

Great, the `--add-platform` explains it all then. Because of that I wasn't sure if there was anything else and I got paranoid because of some commits in the past. All good.

**Pull request merged**
