### PR TITLE
UNSW is now premium

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
What's this failed test?

**Comment by lsf37** [comment]
We haven't figured out yet how to get the website built from a PR from a forked repo. We thought we had it, but it was building the wrong state.

It does work if you push to a branch inside the repo, i.e. in your case

```
git checkout -b premium
git remote add main git@github.com:seL4/website.git
git push --set-upstream main premium
```

And then raise the PR from that branch on github (it might show you an URL you can CMD-double-click when you push).

I can also do that one if you like.

**Comment by gernotheiser** [comment]
let me try...

**Comment by gernotheiser** [comment]
looks like this is good now...

**Comment by lsf37** [comment]
It picks up that the commits in the other PR are identical. If you merge the other one, this one should close automatically as well.

**Comment by gernotheiser** [comment]
looks good

**Pull request merged**
