### PR TITLE
Update board membership

### PR DESCRIPTION
**Pull request by gernotheiser**
Signed-off-by: Gernot Heiser <gernot@unsw.edu.au>

### CODE REVIEW

**Comment by gernotheiser** [comment]
Waiting for pic and blurb for David

**Review by lsf37 — COMMENTED** [review]
We should probably remove the Chief Scientist and Group Leader links next to June's and my name.

**Comment by gernotheiser** [comment]
Also, I forgot, are you on the OC or not?

**Comment by lsf37** [comment]
I'm not on the OC

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
