### PR TITLE
update open video chat schedule

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by axel-h** [comment]
Not sure why the linker checker fails. Locally, the URL https://trustedcomputingcoe.org/summits/2020-summit/ still works for me.

**Comment by lsf37** [comment]
Happy to ignore that part, might have been a temporary thing on their side.

Seeing the date, it occurs to me that 26 Jan is a public holiday in Australia. Not quite sure how to deal with that. I'd be happy to still have the meeting running, but I'd expect not many of the Australian side to show up. Also not sure if I will be able to join myself, and it looks like I can only add UNSW people as co-hosts of the meeting.

**Comment by axel-h** [comment]
Added a note about the holiday for now as marker. If there is a way to open the line it would be nice. Otherwise this has to be cancelled then.

**Comment by lsf37** [comment]
> Added a note about the holiday for now as marker. If there is a way to open the line it would be nice. Otherwise this has to be cancelled then.

Couldn't find a way to do that, but we can shift this one instance by one day. Then Kent, June and I can join and afterwards we proceed with the old schedule.

Will announce the schedule exception on the mailing list + discourse a bit earlier than usual, maybe this week and then again in the week of the meeting.

**Comment by axel-h** [comment]
So, Monday or Wednesday then?

**Comment by lsf37** [comment]
Wednesday

**Review by lsf37 — APPROVED** [review]
Thanks!

**Pull request merged**
